language: c
dist: trusty
sudo: false
group: beta

branches:
    only:
        - 2.7

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - TESTING=cpython

matrix:
  include:
    - os: linux
      language: cpp
      compiler: clang
      env:
        - TESTING="C++ header compatibility"
      before_script:
        - ./configure
      script:
        - echo '#include "Python.h"' > test.cc && $CXX -c test.cc -o /dev/null -I ./Include -I .

# Travis provides only 2 cores, so don't overdue the parallelism and waste memory.
before_script:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.(rst|yml)$)|(^Doc)/'
      then
        echo "Only docs were updated, stopping build process."
        exit
      fi
      ./configure --with-pydebug
      make -j4

script:
  # `-r -w` implicitly provided through `make buildbottest`.
  - make buildbottest TESTOPTS="-j4"
